//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_project_table
    {
        public long id { get; set; }
        public string name { get; set; }
        public short status { get; set; }
        public sbyte enabled { get; set; }
        public short view_state { get; set; }
        public short access_min { get; set; }
        public string file_path { get; set; }
        public string description { get; set; }
    }
}
