//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_bugnote_table
    {
        public long id { get; set; }
        public long bug_id { get; set; }
        public long reporter_id { get; set; }
        public long bugnote_text_id { get; set; }
        public short view_state { get; set; }
        public System.DateTime date_submitted { get; set; }
        public System.DateTime last_modified { get; set; }
        public Nullable<int> note_type { get; set; }
        public string note_attr { get; set; }
        public long time_tracking { get; set; }
    }
}
