//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_user_pref_table
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public long project_id { get; set; }
        public long default_profile { get; set; }
        public long default_project { get; set; }
        public sbyte advanced_report { get; set; }
        public sbyte advanced_view { get; set; }
        public sbyte advanced_update { get; set; }
        public int refresh_delay { get; set; }
        public sbyte redirect_delay { get; set; }
        public string bugnote_order { get; set; }
        public sbyte email_on_new { get; set; }
        public sbyte email_on_assigned { get; set; }
        public sbyte email_on_feedback { get; set; }
        public sbyte email_on_resolved { get; set; }
        public sbyte email_on_closed { get; set; }
        public sbyte email_on_reopened { get; set; }
        public sbyte email_on_bugnote { get; set; }
        public sbyte email_on_status { get; set; }
        public sbyte email_on_priority { get; set; }
        public short email_on_priority_min_severity { get; set; }
        public short email_on_status_min_severity { get; set; }
        public short email_on_bugnote_min_severity { get; set; }
        public short email_on_reopened_min_severity { get; set; }
        public short email_on_closed_min_severity { get; set; }
        public short email_on_resolved_min_severity { get; set; }
        public short email_on_feedback_min_severity { get; set; }
        public short email_on_assigned_min_severity { get; set; }
        public short email_on_new_min_severity { get; set; }
        public short email_bugnote_limit { get; set; }
        public string language { get; set; }
    }
}
