//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_email_table
    {
        public long email_id { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public System.DateTime submitted { get; set; }
        public string metadata { get; set; }
        public string body { get; set; }
    }
}
