//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_custom_field_table
    {
        public int id { get; set; }
        public string name { get; set; }
        public short type { get; set; }
        public string possible_values { get; set; }
        public string default_value { get; set; }
        public string valid_regexp { get; set; }
        public short access_level_r { get; set; }
        public short access_level_rw { get; set; }
        public int length_min { get; set; }
        public int length_max { get; set; }
        public sbyte advanced { get; set; }
        public sbyte require_report { get; set; }
        public sbyte require_update { get; set; }
        public sbyte display_report { get; set; }
        public sbyte display_update { get; set; }
        public sbyte require_resolved { get; set; }
        public sbyte display_resolved { get; set; }
        public sbyte display_closed { get; set; }
        public sbyte require_closed { get; set; }
    }
}
