//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_filters_table
    {
        public long id { get; set; }
        public int user_id { get; set; }
        public int project_id { get; set; }
        public Nullable<sbyte> is_public { get; set; }
        public string name { get; set; }
        public string filter_string { get; set; }
    }
}
