//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_bug_table
    {
        public long id { get; set; }
        public long project_id { get; set; }
        public long reporter_id { get; set; }
        public long handler_id { get; set; }
        public long duplicate_id { get; set; }
        public short priority { get; set; }
        public short severity { get; set; }
        public short reproducibility { get; set; }
        public short status { get; set; }
        public short resolution { get; set; }
        public short projection { get; set; }
        public string category { get; set; }
        public System.DateTime date_submitted { get; set; }
        public System.DateTime last_updated { get; set; }
        public short eta { get; set; }
        public long bug_text_id { get; set; }
        public string os { get; set; }
        public string os_build { get; set; }
        public string platform { get; set; }
        public string version { get; set; }
        public string fixed_in_version { get; set; }
        public string build { get; set; }
        public long profile_id { get; set; }
        public short view_state { get; set; }
        public string summary { get; set; }
        public int sponsorship_total { get; set; }
        public sbyte sticky { get; set; }
        public string target_version { get; set; }
    }
}
