//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_bug_history_table
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public long bug_id { get; set; }
        public System.DateTime date_modified { get; set; }
        public string field_name { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public short type { get; set; }
    }
}
