//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_custom_field_project_table
    {
        public int field_id { get; set; }
        public long project_id { get; set; }
        public short sequence { get; set; }
    }
}
