//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnitrackTma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_news_table
    {
        public long id { get; set; }
        public long project_id { get; set; }
        public long poster_id { get; set; }
        public System.DateTime date_posted { get; set; }
        public System.DateTime last_modified { get; set; }
        public short view_state { get; set; }
        public sbyte announcement { get; set; }
        public string headline { get; set; }
        public string body { get; set; }
    }
}
