//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniTrackTma_TDB_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_tokens_table
    {
        public int id { get; set; }
        public int owner { get; set; }
        public int type { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<System.DateTime> expiry { get; set; }
        public string value { get; set; }
    }
}
