//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniTrackTma_TDB_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_project_version_table
    {
        public int id { get; set; }
        public long project_id { get; set; }
        public string version { get; set; }
        public System.DateTime date_order { get; set; }
        public string description { get; set; }
        public sbyte released { get; set; }
    }
}
