//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniTrackTma_TDB_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_sponsorship_table
    {
        public int id { get; set; }
        public int bug_id { get; set; }
        public int user_id { get; set; }
        public int amount { get; set; }
        public string logo { get; set; }
        public string url { get; set; }
        public sbyte paid { get; set; }
        public System.DateTime date_submitted { get; set; }
        public System.DateTime last_updated { get; set; }
    }
}
