//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniTrackTma_TDB_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_user_profile_table
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public string platform { get; set; }
        public string os { get; set; }
        public string os_build { get; set; }
        public string description { get; set; }
    }
}
