//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniTrackTma_TDB_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_config_table
    {
        public string config_id { get; set; }
        public int project_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> access_reqd { get; set; }
        public Nullable<int> type { get; set; }
        public string value { get; set; }
    }
}
