//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniTrackTma_TDB_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantis_user_table
    {
        public long id { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime last_visit { get; set; }
        public sbyte enabled { get; set; }
        public sbyte @protected { get; set; }
        public short access_level { get; set; }
        public int login_count { get; set; }
        public short lost_password_request_count { get; set; }
        public short failed_login_count { get; set; }
        public string cookie_string { get; set; }
    }
}
