//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniTrackTma_TDB_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OmnitracktmaContext : DbContext
    {
        public OmnitracktmaContext()
            : base("name=OmnitracktmaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mantis_bug_file_table> mantis_bug_file_table { get; set; }
        public virtual DbSet<mantis_bug_history_table> mantis_bug_history_table { get; set; }
        public virtual DbSet<mantis_bug_monitor_table> mantis_bug_monitor_table { get; set; }
        public virtual DbSet<mantis_bug_relationship_table> mantis_bug_relationship_table { get; set; }
        public virtual DbSet<mantis_bug_table> mantis_bug_table { get; set; }
        public virtual DbSet<mantis_bug_tag_table> mantis_bug_tag_table { get; set; }
        public virtual DbSet<mantis_bug_text_table> mantis_bug_text_table { get; set; }
        public virtual DbSet<mantis_bugnote_table> mantis_bugnote_table { get; set; }
        public virtual DbSet<mantis_bugnote_text_table> mantis_bugnote_text_table { get; set; }
        public virtual DbSet<mantis_config_table> mantis_config_table { get; set; }
        public virtual DbSet<mantis_custom_field_project_table> mantis_custom_field_project_table { get; set; }
        public virtual DbSet<mantis_custom_field_string_table> mantis_custom_field_string_table { get; set; }
        public virtual DbSet<mantis_custom_field_table> mantis_custom_field_table { get; set; }
        public virtual DbSet<mantis_email_table> mantis_email_table { get; set; }
        public virtual DbSet<mantis_filters_table> mantis_filters_table { get; set; }
        public virtual DbSet<mantis_news_table> mantis_news_table { get; set; }
        public virtual DbSet<mantis_project_category_table> mantis_project_category_table { get; set; }
        public virtual DbSet<mantis_project_file_table> mantis_project_file_table { get; set; }
        public virtual DbSet<mantis_project_table> mantis_project_table { get; set; }
        public virtual DbSet<mantis_project_user_list_table> mantis_project_user_list_table { get; set; }
        public virtual DbSet<mantis_project_version_table> mantis_project_version_table { get; set; }
        public virtual DbSet<mantis_sponsorship_table> mantis_sponsorship_table { get; set; }
        public virtual DbSet<mantis_tag_table> mantis_tag_table { get; set; }
        public virtual DbSet<mantis_tokens_table> mantis_tokens_table { get; set; }
        public virtual DbSet<mantis_user_pref_table> mantis_user_pref_table { get; set; }
        public virtual DbSet<mantis_user_print_pref_table> mantis_user_print_pref_table { get; set; }
        public virtual DbSet<mantis_user_profile_table> mantis_user_profile_table { get; set; }
        public virtual DbSet<mantis_user_table> mantis_user_table { get; set; }
        public virtual DbSet<mantis_project_hierarchy_table> mantis_project_hierarchy_table { get; set; }
    }
}
